### ISSUE TITLE
Event: What is the definition?

### ISSUE THREAD

**Issue by Dicky-Moe** [syndeno/draft-spinella-event-streaming-open-network#1]
Maybe I missed something, but I didn't find the definition of "event". I know there are different concepts; event in the sense of OLE Automation is different from event in the sense of SIP. There was a discussion somewhere, that only a change of state can be made into a SIP event.
I get the chance to promote SAFU :)
In SAFU, I understand an event as a yet another different thing: as fire-and-forget style.

**Comment by eminwux** [comment]
Hi, sorry for the delay, I have just seen this issue.

The main difference between generic data and an event is that the latter has context information. So, if you consider an IoT device for instance, it could just send data and rely on the receiver to deduce context information. For instance, the receiver could deduce the location of the device based on the source IP of the message. On the other hand, an event is also a piece of data but it includes all the information that the receivers need to process the message, not needing to deduce any information.

Thus, in the case of this hypothetical device, it would send generic data if it just streams bytes with the temperature; it would stream events if each message includes context information (i.e. location, identification, etc.). 

I hope I have explained myself. In any case, I recommend that you look into the book Flow Architectures by James Urquhart.
